#!/bin/sh


rm -r constant/polyMesh
rm -r 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
rm -r log*
rm velocity
rm constant/dynamicMeshDict
rm system/snappyHexMeshDict
rm system/controlDict


rm constant/triSurface/pump_simplified.eMesh.gz
